"""Initial migration

Revision ID: c71e60fc543d
Revises:
Create Date: 2025-11-06 13:52:42.681666

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "c71e60fc543d"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
